const data = [
  "ivyhczwokexltwhsfamqprbnuy",
  "ivjhcjdokexltwwsfamqpabnuy",
  "ivjhczdokebltwgsfydqprbnuy",
  "ivjhcadokexftogsfamqprbnuy",
  "idjhczdokexltwgsfacqprbnuh",
  "ivjhgzookexltwgsfamqjrbnuy",
  "uvjhctdokexltwosfamqprbnuy",
  "ivrhczdokexltwhzfamqprbnuy",
  "ivjhczuxkexltwgsfamqprbney",
  "ivjhczdokemltwgsfadnprbnuy",
  "ifjhczdokexltwgsfamqprbkuf",
  "ivjhkzdokltltwgsfamqprbnuy",
  "ivjuczdhkexltwgsfamqprtnuy",
  "ivjhjzdxkexltwgsfapqprbnuy",
  "ivlhczdoxexltwgsfamqprgnuy",
  "ivjhczdoknxltwgssamqsrbnuy",
  "ivjhczdokexltwgswadqprbruy",
  "ivjhczdokexthwgsfampprbnuy",
  "uvjhczrozexltwgsfamqprbnuy",
  "ivolczdokexltwgsffmqprbnuy",
  "ivjhczibkexltwgsfamoprbnuy",
  "ivjhczdokefltmgsfamqprbouy",
  "ivjhczdobexltngsfamsprbnuy",
  "ivjhczdokexltwvsfxqqprbnuy",
  "dvjhczdokexucwgsfamqprbnuy",
  "kvjhszkokexltwgsfamqprbnuy",
  "ivjhczdokexrtegsfamqprbnus",
  "ivjhctdokexltwglgamqprbnuy",
  "ivjhczdozexutwgsfamqdrbnuy",
  "ivjhczqokemltwgsfakqprbnuy",
  "uvjhczdokexlqwgsfadqprbnuy",
  "ivjhczdohexltwglffmqprbnuy",
  "izjhczdokexltwgsfamqprbsqy",
  "iajhczdokwxltwgjfamqprbnuy",
  "ivjfczdokexllwgslamqprbnuy",
  "ivjhczdoyexltwgsfamqdrbnxy",
  "ivjhczdokekwtwssfamqprbnuy",
  "ivjhcodokexltwgsfamqirxnuy",
  "ihjhhzdokexltwgsfamqlrbnuy",
  "ivjdpzdokexltwfsfamqprbnuy",
  "ivjhcpdokexltwgsfamqqrbruy",
  "qvjhcziokexltwgsfamqprbnny",
  "ivohczdomexltwgsfkmqprbnuy",
  "ivjhczhokhxlywgsfamqprbnuy",
  "ivjhczdokexltwgmffmqprbruy",
  "ivjhczdokqxltwgcfamqprbnyy",
  "ivjhczdokepltwgsfamcprbnay",
  "ivjhczdokexltwgseamqpmbnua",
  "ivjzczdokexltwgszamqplbnuy",
  "ivjhczpokexltwgvfgmqprbnuy",
  "idjhczdokexltwgsxamqprbndy",
  "ivjhczdxkexltwgcgamqprbnuy",
  "ivjhczdckexatpgsfamqprbnuy",
  "ivjrczdorexltwgsfamqprbnvy",
  "ivjoczdokexltwgswamqprbtuy",
  "iylhczdokexltwgsfamqpxbnuy",
  "imxhczdokkxltwgsfamqprbnuy",
  "ivvhczdoktxltwgsfamaprbnuy",
  "ivyhczdokexltwhsfayqprbnuy",
  "ivjhcrdokexltegsfamqprbnum",
  "rvjhezdokexltwgsoamqprbnuy",
  "ivjzczdokexlbwgsfkmqprbnuy",
  "ivjhczdokelltwgsyamqprbnoy",
  "ixjhczdorexltwgsfamqprbuuy",
  "ivjhczpokexdtwglfamqprbnuy",
  "ivjhczdokexltwgfgamcprbnuy",
  "ikjhczdokexltwgsfamqirbnux",
  "ivjhczdopjxltwgsfamqprbnny",
  "ivchczdokexltwgniamqprbnuy",
  "ivjhczdooeqltwgsfamqprbniy",
  "ivjhcldonexltwgbfamqprbnuy",
  "ixjhczdokehltwgsfamqprbnuf",
  "ivjhczdckefltwgsfamqppbnuy",
  "ivjhczdoqrxltwgsfamqprbnun",
  "ivjhczdokcxltwgmfarqprbnuy",
  "ivjhcziorexltqgsfamqprbnuy",
  "ivjhwzdokexltwgnfamqprbcuy",
  "ivjhczdoqexltwgsfazqprunuy",
  "iijhczdokexltwgsyamqprbnug",
  "ivjhczdokexltwgxfamhprbnry",
  "ivjhczdakexltwgsfaeqlrbnuy",
  "ivjhqzdokehltwgsfampprbnuy",
  "ivjhczdokexltwlsfpmyprbnuy",
  "ivjhfzdoktxltwgsfamzprbnuy",
  "ivlhvzdokexltwgsvamqprbnuy",
  "ivjhczdbkexltwgsaamqprfnuy",
  "ivahcedokexltigsfamqprbnuy",
  "cvjhczdokexltwgsfamapibnuy",
  "ivjhczkokbxltwgsfbmqprbnuy",
  "pvjuczdnkexltwgsfamqprbnuy",
  "iyjhczdckexotwgsfamqprbnuy",
  "ivjhzzdokvxltwgsfamqprbnuo",
  "ivjhczdobexltwgsxamqprbnry",
  "ivjhczdokexltwgsfaprprbnub",
  "ivjhczdokexltwgofarqprbkuy",
  "ivjhczdokexltwgbfymqprbnhy",
  "ibjhczdokexltwgsfkmqpvbnuy",
  "ivjhczdzkexlywgsfacqprbnuy",
  "hvdhczdokexltwglfamqprbnuy",
  "ivjhczdokexrtwgsfamqprbsuh",
  "ivjhczhokexltngsfamqpjbnuy",
  "ivjhcsjokexltwgsfaeqprbnuy",
  "ivjmczdokexltmgsfamqpbbnuy",
  "wvjhczdokexltwgsfamkpkbnuy",
  "icjhpzdoaexltwgsfamqprbnuy",
  "ivjmczdhkexltwgsfzmqprbnuy",
  "ivjhczdokexytwgsfamqprbwug",
  "ikjhczdjkexljwgsfamqprbnuy",
  "ivjvcdmokexltwgsfamqprbnuy",
  "ivjhazdorixltwgsfamqprbnuy",
  "ivchczdokexltwgsfamzprenuy",
  "ivjcczdokexlttgsfamqpmbnuy",
  "ibchgzdokexltwgsfamqprbnuy",
  "ivjhczdokepltwgsfamqpeenuy",
  "ivjnwzdokexlrwgsfamqprbnuy",
  "ivjhczdokexitwgsfadqlrbnuy",
  "icjhcrdokexltwgsfamqkrbnuy",
  "ivngczdokexltwgsfamqprbyuy",
  "ivjhuudokexlvwgsfamqprbnuy",
  "ivjhczdnkexltwgsfhmqpxbnuy",
  "itjhczdokexltwvsfamgprbnuy",
  "ivjhcddokexltwgsfakqprbnny",
  "ivjhuzdojexltwfsfamqprbnuy",
  "idjhczdokexltwgsfamqukbnuy",
  "ivjhczdokexlzigsfamqprbngy",
  "ivjwczdokexltwgufamqprbnuo",
  "iijhczdokexltwfsfadqprbnuy",
  "ivjhczdukexdtwgsfamqpsbnuy",
  "idjhczdokexllwgssamqprbnuy",
  "zvjhczdokexrtwgsfamqplbnuy",
  "ivphczdofexltwgefamqprbnuy",
  "ivhhczdokexlpwgsjamqprbnuy",
  "ivjhczdovexltwgsfamqprhnuj",
  "ivjhczdoklxltwgseamqprlnuy",
  "ivjhcqdokexltngsfamqprdnuy",
  "ivjhczdoifxltagsfamqprbnuy",
  "izjhczdokexltwjsramqprbnuy",
  "psjhczdokexlgwgsfamqprbnuy",
  "ivjhcadokexltwgsfsmqwrbnuy",
  "ivjhczdokexltwgsfawqiibnuy",
  "ivjhczkokexhtwgsfamqprbnuk",
  "ivjhcmdukexltwgsfamvprbnuy",
  "ivjlczdokexltwgsfamquibnuy",
  "ivjhczdokexntwgyfamqprbniy",
  "ivjhczdokexltwlsfafqprbnuc",
  "ivjhczdosexltrtsfamqprbnuy",
  "ivjhcznokexbtwgsfafqprbnuy",
  "ivwtczdotexltwgsfamqprbnuy",
  "ivjhvzdokexltigsoamqprbnuy",
  "ivjhcmdokexltwasfamqirbnuy",
  "ivthczdokexltwgsfaydprbnuy",
  "ivjhwzdskexltwgsfamqprbnus",
  "icjhczdosuxltwgsfamqprbnuy",
  "ivjhczdokexltwgstamqbrmnuy",
  "iejhczuoktxltwgsfamqprbnuy",
  "ivjhczdokeqltwgskamqprbniy",
  "ivjhlzdokexltugsfamqprbpuy",
  "iwjqczdckexltwgsfamqprbnuy",
  "ivjhwzdokexluwgsfxmqprbnuy",
  "ivjhczdokexltwgwfwmqprbguy",
  "gvjhczkokexltwgsfgmqprbnuy",
  "ivjhczdoyexlhwgsfamqprbnoy",
  "cvjhczdokexltwgsfomqprinuy",
  "vvmhczdokexltwgsfamqprbnun",
  "vvjhczdokexltwgsftmfprbnuy",
  "ivkhckdokhxltwgsfamqprbnuy",
  "iyjhczdkkexltjgsfamqprbnuy",
  "ivlhczdokexltwgsfamqyrbhuy",
  "tvjhmzdokexltwgsfamqorbnuy",
  "ivjhczdokexltwvsfamqprbnxi",
  "ivjhczdowexltwgswamqerbnuy",
  "wvjiczdomexltwgsfamqprbnuy",
  "ivjpizdokexltwgvfamqprbnuy",
  "ivjhuzdokexlzwgspamqprbnuy",
  "ivjhczdokeyltwgkfamqprdnuy",
  "jvjhczdokexlnwgsfamqirbnuy",
  "ivjheidokexltwvsfamqprbnuy",
  "mvjhczdokexltwgsfamqyrsnuy",
  "ivjhazdykexltwgsramqprbnuy",
  "ivjkcodokexltwgsxamqprbnuy",
  "ikjhczdoktxltwgpfamqprbnuy",
  "ivjhyzdfkexmtwgsfamqprbnuy",
  "ivohczdokexltugsfamqprynuy",
  "ivjkczdqkexltwgshamqprbnuy",
  "ivjhczdokexltwgskamqynbnuy",
  "icjhczdokexltwgofamrprbnuy",
  "ivjhlzdokealtwgsfamqsrbnuy",
  "ivehczdybexltwgsfamqprbnuy",
  "ovjhczdokexltwgsfamqirbnuo",
  "ivjoczdokexltwgsfamqurbnty",
  "ivjmczdokexltwgsfrmqprnnuy",
  "ivjhczdowpxltwgbfamqprbnuy",
  "ivjhczdokexltwfsfamqkrgnuy",
  "ivjhwzdokexltwgsfavqprbnuq",
  "jvjhczdokexltwgsiamqprbnny",
  "ivjhlzdouexltwfsfamqprbnuy",
  "ivjhczdokexltwgsfamqbrbnlv",
  "iwjhczdokexltwgsfapqprbnqy",
  "idjhczdokexltwgsaamqrrbnuy",
  "ivjhjzdopepltwgsfamqprbnuy",
  "ivjmczdokejltwgsfamqpbbnuy",
  "ivjhczdokexltwgsuamdprvnuy",
  "injhczdokexltwgefamqurbnuy",
  "iujhczdokexltwgsaamqjrbnuy",
  "ivjhczdokexltwgvfaaqprbnly",
  "ivehczdokexltwgsfamqppbnui",
  "ivxhczdodexltwgsfamqplbnuy",
  "ivjhczfokexltwgsfamqpwbauy",
  "ivjhcztwkexhtwgsfamqprbnuy",
  "ivjeczdokexltygsfmmqprbnuy",
  "ivjhchdokexltwgsmameprbnuy",
  "ivkhczdoklxltwggfamqprbnuy",
  "ivjhczdzkexltwhsfamqprjnuy",
  "ivjhcedokeultngsfamqprbnuy",
  "ivjhczdokexvtwgseabqprbnuy",
  "ivjhczdooexltlgsfamqpibnuy",
  "ivjgczvosexltwgsfamqprbnuy",
  "ivlhczwokexltwgsfamqmrbnuy",
  "lvjhczdokexutwgsfamrprbnuy",
  "ivahczdokexpdwgsfamqprbnuy",
  "ivjhcznokexltwhsfamqpnbnuy",
  "ivjhczdpkyxltwgbfamqprbnuy",
  "ivjhnzdokexltwgsftmqprinuy",
  "ivihczdokexltnhsfamqprbnuy",
  "ivjhcbdokevltwgsfamqprbauy",
  "hgjoczdokexltwgsfamqprbnuy",
  "dvjhczdckexltwgsfamqpybnuy",
  "ivjhcadokesltwgsfsmqwrbnuy",
  "ivjhwzdokexlttgsfamqprbney",
  "ivjhcidokexltwgofamqfrbnuy",
  "ivokwzdokexltwgsfamqprbnuy",
  "ivjiczdokexltwgsfaqqarbnuy",
  "ivjhczdokexqtwfsfamgprbnuy",
  "ivjhczdokealtwgsfamqerbnqy",
  "ivjhczdskexltwgsfamqprznuu",
  "ivjhwzdokexltwjsfdmqprbnuy",
  "ivjhczaokexlzwgsfamqprbnus",
  "ivjhczdokexltwosfamqnrbnux",
  "ivjhczdokexlqwgsfamwprcnuy",
  "ivjhczdqkexltwgswamqpcbnuy",
  "ijjhczdokexnttgsfamqprbnuy",
  "ivjhcedckexltwgsfamqprbnpy",
  "ivjhczdokeyltwgsfamqshbnuy",
  "ivjhczdokexltsgsfamqpmznuy",
  "ivjlczdtkeiltwgsfamqprbnuy",
  "ivjhczdokexltwgsfkmtprbnby",
  "ivjhnzdozexltwgsfamqprbnuc",
  "xqjxczdokexltwgsfamqprbnuy",
  "ivjhczdokeyltwgsfamqnrbnuw",
  "ivjwczgokexltwgsfamvprbnuy"
];

window.onload = () => {
  loop1: for (let i = 0; i < data.length; i++) {
    const stringOne = data[i];
    const dataWithOutCurrentString = data.filter(x => x !== stringOne);

    loop2: for (let j = 0; j < dataWithOutCurrentString.length; j++) {
      let strikes = 0;
      let diffingPosition = null;

      const stringTwo = dataWithOutCurrentString[j];
      const stringOneArray = [...stringOne];
      const stringTwoArray = [...stringTwo];

      loop3: for (let k = 0; k < stringOneArray.length; k++) {
        const firstStringLetter = stringOneArray[k];
        const secondStringLetter = stringTwoArray[k];

        if (firstStringLetter !== secondStringLetter) {
          strikes++;
          if (strikes >= 2) {
            break loop3;
          }
          diffingPosition = k;
        }
        if (k + 1 === stringOneArray.length && strikes < 2) {
          console.log("FOUND THE BOXES!");
          console.log(`Boxes are: ${stringOne} / ${stringTwo}`);
          console.log(
            `Paste this solution: ${stringOne.slice(0, diffingPosition) +
              stringOne.slice(diffingPosition + 1)}`
          );
          break loop1;
        }
      }
    }
  }
};
